### ISSUE TITLE
Trouble when running "rake db:migrate"

### ISSUE THREAD

**Issue by msarit** [kjleitz/cadu#2]
Hello there! I'm installing this app locally on macOS using postgresql. When I run rake db:migrate (per your instructions), I get the following errors:

```
== 20170314173749 CreateUsers: migrating ======================================
-- create_table(:users)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "assistants" does not exist
: CREATE TABLE "users" ("id" serial primary key, "name" character varying, "email" character varying, "password_digest" character varying, "assistant_id" integer, "role" integer DEFAULT 0, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, CONSTRAINT "fk_rails_930843398c"
FOREIGN KEY ("assistant_id")
  REFERENCES "assistants" ("id")
)
/Users/aritokwu/rubyapps/cadu/db/migrate/20170314173749_create_users.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "assistants" does not exist
: CREATE TABLE "users" ("id" serial primary key, "name" character varying, "email" character varying, "password_digest" character varying, "assistant_id" integer, "role" integer DEFAULT 0, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, CONSTRAINT "fk_rails_930843398c"
FOREIGN KEY ("assistant_id")
  REFERENCES "assistants" ("id")
)
/Users/aritokwu/rubyapps/cadu/db/migrate/20170314173749_create_users.rb:3:in `change'

Caused by:
PG::UndefinedTable: ERROR:  relation "assistants" does not exist
/Users/aritokwu/rubyapps/cadu/db/migrate/20170314173749_create_users.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
I would **truly** appreciate your help in figuring this out 🙏🏾

**Comment by msarit** [comment]
More info: I commented out `t.belongs_to :assistant, foreign_key: true` from the create_users migration, then ran `rake db:migrate`. I got the following error:

```
== 20170314173749 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0131s
== 20170314173749 CreateUsers: migrated (0.0137s) =============================

== 20170314174600 CreateTasks: migrating ======================================
-- create_table(:tasks)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "clients" does not exist
: CREATE TABLE "tasks" ("id" serial primary key, "title" character varying, "content" text, "due_date" timestamp, "client_id" integer, "status" integer DEFAULT 0, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, CONSTRAINT "fk_rails_d3fa40fd45"
FOREIGN KEY ("client_id")
  REFERENCES "clients" ("id")
)
/Users/aritokwu/rubyapps/cadu/db/migrate/20170314174600_create_tasks.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "clients" does not exist
: CREATE TABLE "tasks" ("id" serial primary key, "title" character varying, "content" text, "due_date" timestamp, "client_id" integer, "status" integer DEFAULT 0, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, CONSTRAINT "fk_rails_d3fa40fd45"
FOREIGN KEY ("client_id")
  REFERENCES "clients" ("id")
)
/Users/aritokwu/rubyapps/cadu/db/migrate/20170314174600_create_tasks.rb:3:in `change'

Caused by:
PG::UndefinedTable: ERROR:  relation "clients" does not exist
/Users/aritokwu/rubyapps/cadu/db/migrate/20170314174600_create_tasks.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
